version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      # 本機 host : container host
      - 9911:9911
    container_name: run_frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 7654:7654
    container_name: run_backend
